title: Evan Nevermore's Test Lab
description: An overview of my test lab and my projects
show_downloads: false
name: Mr.Nevermore
theme: jekyll-theme-cayman
gist:
  noscript: false
lsi: false
safe: true
incremental: false
highlighter: rouge

# Google Analytics
google_analytics: G-7H0ZWJFEJZ

# JavaScript
head_scripts:
  - /assets/js/read-progress.js